name: gan_project
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9.0
  - numpy=1.20.3
  - scipy=1.7.1
  - keras=2.7.0
  - tensorflow=2.7.0
  - flake8=4.0.1
  - pip=22.0.4
  - pyyaml=6.0
  - matplotlib=3.5.2

